# FUNDING.yml
# Documentation: https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/adding-a-funding-file-to-your-repository

github: byraphaelmedeiros
custom: ["https://buymeacoffee.com/byraphaelmedeiros"]
